---
- name: Configure Ubuntu MOTD
  include: ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version >= "16"

- name: Configure Debian MOTD
  include: ubuntu.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version >= "9"

- name: Configure CentOS MOTD
  include: centos.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version >= "7"
