---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for Tautulli to succesfully restart
      ansible.builtin.wait_for:
        port: 8181

    - name: Test Tautulli webinterface
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:8181/home"
